// <auto-generated />
namespace MovieCustomerMvcAppWithAuthen.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class GenreIdmadeasforeignkeyinmovietable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GenreIdmadeasforeignkeyinmovietable));
        
        string IMigrationMetadata.Id
        {
            get { return "202008240648424_GenreId made as foreign key in movie table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
